### ISSUE TITLE
RTL programs on NPO page

### ISSUE THREAD

**Issue by Vogeltak** [StandardInput/Nedflix-api#1]
dataArr does not get cleared between different program getters. It keeps all previous programs retrieved and passes them on.

**Comment by KeizerDev** [comment]
Good work! :+1:

**Comment by Vogeltak** [comment]
We could also clear dataArr before each request. But this way all data stays in its variables.

**Comment by KeizerDev** [comment]
I know, I was preferring the second option so we keep it constant because every `dataArr` is equal qua data..

**Comment by Vogeltak** [comment]
Wait, what do you mean by that? Do you prefer different variables for the data of npo and rtl?

**Comment by KeizerDev** [comment]
No, it was not. I prefer just using one single variable to keep constancy because the data that is inside the `dataArr` is all equal, all the arrays have the same types so it wouldn't make sense to use different vars inside the api.

**Comment by Vogeltak** [comment]
Then we should clear `dataArr` before pushing new values to it.

**Comment by KeizerDev** [comment]
Jup
